### ISSUE TITLE
Game boy decompressor

### ISSUE THREAD

**Issue by untoxa** [emmanuel-marty/apultra#11]
I adapted i8080 decompressor for GBZ80: https://github.com/untoxa/UnaPACK.GBZ80 you may add a link to it, if you wish. thank you.

**Comment by emmanuel-marty** [comment]
Done, thank you! I hope you enjoy the compressor.

Note that there is a generic z80 depacker by specke in the asm/Z80 folder (it is currently the fastest known decompressor for the aPLib format on z80, by ~18% or so compared to the previously fastest code). Maybe this will be useful to you as well.
