### ISSUE TITLE
I adapted your code to an 8086 (segmented memory) depacker

### ISSUE THREAD

**Issue by ecm-pushbx** [emmanuel-marty/apultra#15]
Like I did with your [LZSA2 depacker](https://github.com/emmanuel-marty/lzsa/issues/61) before, I adapted your "size-optimized aPLib decompressor for 8088" for use in my 86-DOS kernel/executable format. It is [available in my hgweb repo](https://hg.ulukai.org/ecm/inicomp/file/4c6ae7774f3a/apl.asm).

The changes that I had to do:

1. Use bp for stack frame to access variables throughout
2. Count down remaining lengths of source and destination (needed to detect success or failure with overlapping buffers, also provides simple error checking)
3. Use far pointers throughout, which are normalised after every use
4. Add stack frame variables for the high words of distance and gamma
5. Allow matches with >= 64 KiB distance and/or >= 64 KiB length
6. Allow overlapping buffers by checking the pointers after matches and match bytes

**Comment by emmanuel-marty** [comment]
Thanks! I will link to your Mercurial repos for both depackers. If you use it in production I'll be happy to link to your projects as well.

**Comment by emmanuel-marty** [comment]
Thanks again, link added to the README

**Comment by ecm-pushbx** [comment]
In https://github.com/emmanuel-marty/apultra/commit/8f354ae2aae022155d461754f45363fc096aceae did you mean to delete the link to the i8080 decompressors?
