### ISSUE TITLE
strange bug in unaplib_68000.S

### ISSUE THREAD

**Issue by arnaud-carre** [emmanuel-marty/apultra#16]
Hi!
thanks for making apultra, pretty easy to integrate. I noticed a strange behavior with unaplib_68000.S and some packed files. At first I though it was a packer bug but it seems to be a depacker bug. ( the specific file is depacking properly using another 68k aplib decoder ). I didn't investigated the issue but I attached problematic file if you're interested. ( just pack it, and it doesn't depack properly using unaplib_68000.S: The first byte is literal (normal) and the second token try to depack a string with "0" offset (producing bad output data). 
cheers
Arnaud
[sprite.zip](https://github.com/emmanuel-marty/apultra/files/7157227/sprite.zip)

**Comment by emmanuel-marty** [comment]
Thank you, I am definitely interested! I will try packing and unpacking your test file. There are some automated self-tests but it's entirely possible they missed this somehow.

**Comment by emmanuel-marty** [comment]
I seem to have made a stupid assumption. Under .short_match: , below addx.b d0,d0 and above beq.s .write_zero, can you add a tst.b d0, so it looks like:

               addx.b d0,d0         ; shift second bit into d0
               tst.b d0
               beq.s .write_zero    ; if offset is zero, write a 0

For me, this fixes the issue, but it's a stupid, wider problem that I didn't see because my private testsuite (that unpacks through a 68k emulator etc) zeroes out all memory first.

Let me know; I'll make sure I make a proper fix

**Comment by arnaud-carre** [comment]
Hi! I confirm your fix is working, good catch! I wasn't aware of the very specific Z flag behavior when using addx instruction. And bad luck it worked for you because it copy a "$00" byte because your dest memory  was cleared. Bugs are smarter than us :)
thanks!

**Comment by emmanuel-marty** [comment]
Thanks for your help tracking this down!
