### ISSUE TITLE
Is it possible to print the "Safe Distance" as in LZSA?

### ISSUE THREAD

**Issue by realmml** [emmanuel-marty/apultra#3]
Bonjour Emmanuel,

I just have been using LZSA previously and one feature that I love is that you can get the "Safe Distance" for decrunching data over itself. For me, this information is great for making a better use of the limited ram in my games for old 8 bit computers. 

Would it be possible to add this feature to apultra? Because the compression ratio of apultra is even better, it would be an improvement for my projects in those limited machines.

Merci! :)

**Comment by emmanuel-marty** [comment]
Hey,

That's a good idea -- implemented in d565801500420af3271a578126946415884a4b75

I can make a new binary release with this if you need (along with a few other small improvements)

**Comment by realmml** [comment]
Magnifique Emmanuel! :)

I just compiled apultra and made a very fast test. Everything looks that it is working perfectly and after adding support for apultra in my last project, I just saved 10 KBs.

Merci! :)
